### ISSUE TITLE
Can't create server socket in certain ports

### ISSUE THREAD

**Issue by panreyes** [many-fac3d-g0d/ServeIt#13]
I somehow managed to compile the latest version (although I couldn't compile it twice, just once for some reason) and it looks like it wasn't able to create server socket or find out wifi IP or SSID:
```
....304 - I flutter : Interfaces Detected Instance of 'Future<List<NetworkInterface>>'
....304 - I flutter : User inputted dir /storage/emulated/0/share
....304 - I flutter : User inputted port 737
....306 - I flutter : is wifiName there ? : null
....306 - I flutter : wifiIPv4 : null
....306 - E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 0.0.0.0, port = 737
....306 - E flutter : #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032)
....306 - E flutter : <asynchronous suspension>
....306 - E flutter : #1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812)
....306 - E flutter : <asynchronous suspension>
....306 - E flutter : #2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097)
....306 - E flutter : <asynchronous suspension>
....306 - E flutter : #3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186)
....306 - E flutter : <asynchronous suspension>
....306 - E flutter : #4      _HomeState.startServer.<anonymous closure> (package:flutter_http_server/main.dart:183)
....306 - E flutter : <asynchronous suspension>
....306 - E flutter :
....307 - I flutter : Interface Detected : wlan0
....307 - I PLogger : {ServeIt}  {startServer()}  {User inputted dir /storage/emulated/0/share}  {08 April 2024 10:20:40 PM}  {INFO}
....308 - I flutter : IP Type : IPv4
....308 - I flutter : IP Type : **192.168.1.168**
....310 - I PLogger : {ServeIt}  {startServer()}  {User inputted port 737}  {08 April 2024 10:20:40 PM}  {INFO}
....310 - I PLogger : {ServeIt}  {startServer()}  {is wifiName there ? : null}  {08 April 2024 10:20:40 PM}  {INFO}
....311 - I PLogger : {ServeIt}  {startServer()}  {wifiIPv4 : null}  {08 April 2024 10:20:40 PM}  {INFO}
```

It seems that it still could find out my wifi IP, it just didn't assign it to $wifiIPv4.

My Android device is a Samsung Galaxy A52S with Android 14 (One UI 6.0)

Update: It seems to work correctly when I select other ports!

**Comment by many-fac3d-g0d** [comment]
@panreyes Ports which are < 1024 are privileged ports in linux/android, you would need root access in case of linux to bind to these ports & in case of android it is a limitation (check https://issuetracker.google.com/issues/36909525 for more info). I actually remember implementing a min port formatter but seems like I became liberal on the choice of ports from user 😁. There is a fix that needs to be made [here](https://github.com/many-fac3d-g0d/ServeIt/blob/05aa0b72757520886b3e124ae4d2acc17bad90da/lib/main.dart#L438). Will work on this once done with the current build
